### ISSUE TITLE
Prometheus unable to scrape endpoints on cf app with routes associated

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/cf-for-k8s-metric-examples#2]
I was inspired by the [go-app-with-metrics example](https://github.com/cloudfoundry/cf-for-k8s-metric-examples/blob/9618d40765c86f7fcaab5bb9aaa8719f9b78f95b/go-app-with-metrics/manifest.yml) and [setup running the `prometheus-operator` colocated with cf-for-k8s](https://github.com/aegershman/deployments/blob/master/cf-for-k8s/config/prometheus-operator/values.yml) and using an [application deployed using the same `prometheus.io` annotations](https://github.com/aegershman/deployments/blob/master/cf-for-k8s/config/cf/values/example-docker-cf-manifest-hash-browns-no-web.yml) -- which, tangentially, personally I think this is very cool, powerful, and could open the door to other interesting possibilities for plumbing together CF and other systems. anyhow--

When there are no routes associated to the application and the app is just a regular `process`, prometheus is able to scrape the eirini-built pod against the port `/metrics` is exposed on:

<img width="1263" alt="with-no-route" src="https://user-images.githubusercontent.com/5619476/85211223-9b050b80-b30c-11ea-82ee-d8908eb80461.png">

When there are routes associated to it, prometheus appears unable to scrape the pod, `svc`, or generally any `endpoint` associated to it:

<img width="1267" alt="with-route-associated" src="https://user-images.githubusercontent.com/5619476/85211265-05b64700-b30d-11ea-8546-60ef9e810fe8.png">

I also haven't had success using different ports e.g. `prometheus.io/port: 80`:

<img width="1255" alt="with-route-on-80" src="https://user-images.githubusercontent.com/5619476/85211408-7ad64c00-b30e-11ea-8e5d-75efc7296596.png">

... or using a ServiceMonitor or PodMonitor against the pod's associated `svc`, etc.

I haven't dug too deep into this, mostly trial and error; I'm assuming it has to do with how routing gets wired up via istio ("something-something proxy?"). Forgive me for not having more definitive explanation, I just wanted to get this issue out there before digging around too much more.

Is this to be expected for the time being? any success with having prometheus scrape pods which have cf routes associated to them? thanks all 👍 

EDIT this may have something to do with the pods prometheus leverages to perform scrapes requires istio sidecar injection. maybe. I'll just go poke around and find out.

**Comment by hev** [comment]
Thanks @aegershman - we have also been looking at this and there appears to be a couple of considerations.

1. Annotations are not quite working fully declaratively for us using either cf6 or cf7. As a work around we updated some instructions about using cf6 curls but we hope to get this to a fully declarative UX in cf7. 
1. Istio sidecar is getting in the way of our scraping. We are working to figure out how to deploy prometheus to address this.

**Comment by aegershman** [comment]
1.) the annotations for the cf manifest have worked for me as long as I wrap the booleans of "true" in quotes

2.) I believe I need to label the prometheus-operator's namespace with `istio-injection: enabled` to have the sidecar proxy injected into the prometheus pods which permits querying:

```yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator
  labels:
    istio-injection: enabled
```

or

```sh
kubectl label --overwrite namespace prometheus-operator "istio-injection=enabled"
```

And as for the prometheus deployment itself, using the prometheus-operator helm chart, a snippet of the values look like this:

```yml
prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      podAnnotations:
        sidecar.istio.io/inject: "false"
  podAnnotations:
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
  logLevel: debug

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio
    hosts:
      - prometheus.vcap.me
  logLevel: debug
  retention: 10m
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    podMetadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
```

I've had success with this so far 👍

**Comment by heycait** [comment]
hey @aegershman what version of CF CLI are you using? Even using quotes in the app manifest, we haven't gotten this working with cf6 or cf7. 

we just merged in some changes to master branch with newer instructions including the network policy we need. check it out and let us know if it works for you

**Comment by aegershman** [comment]
1.) I'm using cf7 (on mac catalina 10.15.5, using zsh):

```sh
cf -v
cf version 7.0.1+fb3f929c2.2020-06-24
```

Here's an example of an app manifest (which uses a docker image on push) with metadata inlined in the manifest:

```yml
---
applications:
  - name: hash-browns
    instances: 1
    memory: 256M
    routes:
      - route: hash-browns.apps.vcap.me
    docker:
      image: alexellis2/hashbrowns:1.2.0
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: 8080
        prometheus.io/path: /metrics
```

and pushed with

```sh
cf push -f hash-browns-docker-no-routes.yml
```

Is it giving you grief with a 500 error? Let me know if I can help with any more information. This could be something peculiar to do with how quotes are being applied or something.

2.) Were you able to successfully scrape pods which have a route associated to them? I'm able to scrape pods which don't have any routes (and thus no k8s svc or virtual service) associated to them, but as soon as a route is applied, [I get 503s when trying to scrape the pod itself](https://github.com/aegershman/deployments/blob/master/cf-for-k8s/config/prometheus-operator/user/helm/values.yml). I'm assuming this has to do with how istio/envoy proxying gets set up, but I haven't 100% pinned it down yet. Curious, did you all do anything special with the prometheus deployment besides `--set server.labels...`? 

Also, this isn't the end of the world or anything; to be honest this is more of a learning exercise for me, and a razzle-dazzle proof of value I can use to show to my employer 😉  as opposed to a "definitive production strategy for metrics". So if this doesn't quite work out, it's no worries.

Thanks again for your help and time I appreciate it

**Comment by heycait** [comment]
Interesting! We just used `cf push` without specifying the file since we named it `manifest.yml`. We also weren't using a docker image and used the go buildpack instead. We were able to `cf push` this app using cf7 cli without the manifest so we figured it was the manifest breaking something.

Here's our manifest.
```
---
applications:
- name: go-app-with-metrics
  buildpacks:
  - https://github.com/cloudfoundry/go-buildpack.git
  health-check-type: process
  instances: 2
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "2112"
      prometheus.io/path: "/metrics"
  no-route: true
```

We weren't encountering the 500 issue after we started using the quotes. We were getting this staging failed message:
```
Staging app and tracing logs...
StagingTimeExpired - Staging time expired: staging failed
FAILED
``` 

We did some more testing and it turns out the issue was using `buildpacks` regardless of using a buildback url or trying to use one locally. Finally got the application manifest to work by removing that section and all the annotations and everything looks good.

I spoke with @hev and decided we'll keep the issue with the routes as a separate investigation. We'll update you when we get there. 😺
